-- Question 5, see .md file for details.


/*

	Part 1 / 2: Create initial JOIN table view

	Purpose:

		- Establish the table which Q5 will be answered from
		- Key Changes include adding price_usd column from country_fee 

*/

SELECT
	usern.*,
	c_fee.price_usd
FROM
	netflix_user_data AS usern
LEFT JOIN
	country_fee AS c_fee
USING (region, sub_plan) -- Since both names of columns is the same in both tables, used USING function.

/*
	
	Part 2/2: Find total revenue generated by each region and subscription plan

	Purpose:

	- Inform marketing team on best-performing subscription plans per region, make soft recommendations
	on next steps.
	- Use a sub_length * usd_price to determine total revenue for each subscrip'tion plan, repeated for
	each region.

*/

SELECT
	region,
	/* The following three SELECT statements return total revenue count (price * sub_length)
	when sub_plan requirements are met */
	SUM(CASE WHEN sub_plan = 'Basic'
		THEN c_fee.price_usd * usern.sub_length ELSE 0 END) AS basic_revenue,
	SUM(CASE WHEN sub_plan = 'Standard'
		THEN c_fee.price_usd * usern.sub_length ELSE 0 END) AS standard_revenue,
	SUM(CASE WHEN sub_plan = 'Premium'
		THEN c_fee.price_usd * usern.sub_length ELSE 0 END) AS premium_revenue,
	/* Returns total revenue for each region */
	SUM(c_fee.price_usd * usern.sub_length) AS total_revenue
FROM
	netflix_user_data AS usern
LEFT JOIN
	country_fee AS c_fee
USING (region, sub_plan)
/* USING function used for code cleaniness */
GROUP BY
	region
ORDER BY
	region


